DROP VIEW ISI.FG_ALARMS;

/* Formatted on 2016-12-12 08:21:24 (QP5 v5.256.13226.35510) */
CREATE OR REPLACE FORCE VIEW ISI.FG_ALARMS
(
   ALARM_DATE,
   TAG,
   DESCRIPTION,
   COUNTER_1,
   COUNTER_2,
   RECOMENDATION,
   DETECTOR_TYPE,
   COMMENTS
)
AS
     SELECT FG_MAINT_ALARMS.ALARM_DATE,
            FG_MAINT_ALARMS.TAG,
            FG_MAINT_ALARMS.DESCRIPTION,
            FG_MAINT_ALARMS.COUNTER_1,
            FG_MAINT_ALARMS.COUNTER_2,
            FG_RECOMENDATION.DESCRIPTION AS RECOMENDATION,
            FG_DETECTOR_TYPE.DESCRIPTION AS DETECTOR_TYPE,
            FG_MAINT_ALARMS.COMMENTS
       FROM FG_MAINT_ALARMS, FG_RECOMENDATION, FG_DETECTOR_TYPE
      WHERE     FG_MAINT_ALARMS.RECOMENDATION_ID = FG_RECOMENDATION.ID
            AND FG_MAINT_ALARMS.TYPE_ID = FG_DETECTOR_TYPE.ID
   ORDER BY FG_MAINT_ALARMS.ALARM_DATE DESC, DETECTOR_TYPE, RECOMENDATION;
