DROP TABLE ISI.FG_DETECTOR_TYPE CASCADE CONSTRAINTS;

CREATE TABLE ISI.FG_DETECTOR_TYPE
(
  ID           INTEGER,
  DESCRIPTION  VARCHAR2(256 BYTE)               NOT NULL, 
  CONSTRAINT FG_DETECTOR_TYPE_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
TABLESPACE CIM21
RESULT_CACHE (MODE DEFAULT)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOPARALLEL
NOMONITORING;


-- Index FG_DETECTOR_TYPE_PK is created automatically by Oracle with index organized table FG_DETECTOR_TYPE.
