DROP TABLE ISI.FG_RECOMENDATION CASCADE CONSTRAINTS;

CREATE TABLE ISI.FG_RECOMENDATION
(
  DESCRIPTION  VARCHAR2(1000 BYTE)              NOT NULL,
  ID           INTEGER, 
  CONSTRAINT FG_RECOMENDATION_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
TABLESPACE CIM21
RESULT_CACHE (MODE DEFAULT)
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOPARALLEL
NOMONITORING;


-- Index FG_RECOMENDATION_PK is created automatically by Oracle with index organized table FG_RECOMENDATION.
